TEP-613: таблица в quill
egor1996em2/quill-table pull request #5
Opened 2024-11-12 15:44 UTC by egor1996em2

2024-11-13 11:36 UTC, pashafish requested changes

2024-11-13 11:36 UTC, pashafish commented on src/modules/table-selection.js
>      helpLinesInitial() {
При первом клике в ячейку новой таблицы она не выделяется синей рамкой
<img width="800" alt="Снимок экрана 2024-11-13 в 16 36 13" src="https://github.com/user-attachments/assets/a28d0cc6-254b-438a-ac9b-244281d9c6e6">

2024-11-13 14:00 UTC, egor1996em2 commented on demo/demo.html
Демка нужна вот почему.

Этот плагин идет как отдельный пакет, который используется вместе с quill.
Изначально я предполагал, что можно будет просто сделать npm link и все будет здорово: покет подятнется, все будет работать и радовать глаз, но quill передал привет)

В общем quill сделан так, что он предполагаетч, что на странице может быть только одна версия пакета quill и все действия производятся только с ней.
А при npm link происходит странность вот какая: код плагина идет в инстанс quill, который находится в node_modules плагина quill-table, а вот в tildaplugins берется тот, что у него в node_modules.
Из-за этого локальная разработка сводится к тому, что надо выпускать тестовые версии пакета, что долго и в целом грустно.
Поэтому исходную демку оставил для удобства разработки.
В будущем ожно будет заменить ее на storybook, например.

2024-11-13 14:18 UTC, egor1996em2 commented on src/quill-table.js
>  }
Поправил

2024-11-13 14:18 UTC, egor1996em2 commented on dist/quill-table.css
> +.quill-table-operation-menu {
Обновил историю

2024-11-14 10:29 UTC, pashafish commented on dist/quill-table.css
> +.quill-table-operation-menu {
Кажется тут вертикальный паддинг великоват у пунктов. Не такой как в дропдауне в квилле после апдейта

<img width="208" alt="Снимок экрана 2024-11-14 в 15 28 46" src="https://github.com/user-attachments/assets/7e5d934e-e152-4202-bc24-e8e6036eff5f">

2024-11-14 15:07 UTC, egor1996em2 commented on dist/quill-table.css
> +.quill-table-operation-menu {
Поправил

2024-11-21 07:48 UTC, merged